#!/bin/bash
source /root/.environment
(
set
for IP in $IPS ; do
    TABLES=$(cqlsh $IP -e "use $KEYSPACE; describe tables")
    [ $? -ne 0 ] && echo $IP not reachable && continue

    BACKUP_TS=$(date +%s)
    LABEL="$(date +MON%m_DAY%d_HR%H)_$IP"
    BACKUP_DIR="/var/backup/cassandra"
    mkdir -p $BACKUP_DIR/$LABEL
    CQLSH="CONSISTENCY QUORUM;"
    for TABLE in $TABLES; do
      CQLSH="$CQLSH copy $KEYSPACE.$TABLE to '$BACKUP_DIR/$LABEL/${TABLE}.csv';"
    done
    cqlsh $IP -e "$CQLSH"
    cd $BACKUP_DIR
    tar cvzf $LABEL.tar.gz $LABEL
    rm -rf $LABEL
    break
done
)>> /var/backup/log.txt 2>&1
